
modLoader="javafml" #mandatory
loaderVersion="{40,}" #mandatory
license="GNU GPLv2" #mandatory

[[mods]]
modId="rogueguns"
version="1.0.0"
displayName="Rogue Guns"
authors="Andro"
description="An Addon to Just Enough Guns"

[[dependencies.rogueguns]]
    modId="forge"
    mandatory=true
    versionRange="[46, 48)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rogueguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.rogueguns]]
    modId="jeg"
    mandatory=true
    versionRange="[0.3.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rogueguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.6.16,)"
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"